"""core schema

Revision ID: d6521992dd73
Revises: 85cc87b01541
Create Date: 2026-02-19 10:56:48.397179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6521992dd73'
down_revision: Union[str, None] = '85cc87b01541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('learner', 'creator', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('creator_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('learner_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.Enum('en', 'es', 'fr', name='language'), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_learner_profile_level'), 'learner_profile', ['level'], unique=False)
    op.create_index(op.f('ix_learner_profile_target_language'), 'learner_profile', ['target_language'], unique=False)
    op.create_table('streak',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date_utc', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('video_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('en', 'es', 'fr', name='language'), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='contentstatus'), nullable=False),
    sa.Column('video_url', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_content_creator_id'), 'video_content', ['creator_id'], unique=False)
    op.create_index('ix_video_content_feed', 'video_content', ['language', 'level', 'status', 'published_at'], unique=False)
    op.create_index(op.f('ix_video_content_language'), 'video_content', ['language'], unique=False)
    op.create_index(op.f('ix_video_content_level'), 'video_content', ['level'], unique=False)
    op.create_index(op.f('ix_video_content_published_at'), 'video_content', ['published_at'], unique=False)
    op.create_index(op.f('ix_video_content_status'), 'video_content', ['status'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['video_content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_table('xp_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('quiz_completed', 'streak_bonus', name='xpreason'), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_date_utc', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['video_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_event_created_date_utc'), 'xp_event', ['created_date_utc'], unique=False)
    op.create_index('ix_xp_event_user_date', 'xp_event', ['user_id', 'created_date_utc'], unique=False)
    op.create_index(op.f('ix_xp_event_user_id'), 'xp_event', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('multiple_choice', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('completed_date_utc', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['video_content.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempt_completed_at'), 'quiz_attempt', ['completed_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_completed_date_utc'), 'quiz_attempt', ['completed_date_utc'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_content_id'), 'quiz_attempt', ['content_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_user_id'), 'quiz_attempt', ['user_id'], unique=False)
    op.create_index('ix_quiz_attempt_xp_enforce', 'quiz_attempt', ['user_id', 'content_id', 'completed_date_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_attempt_xp_enforce', table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_user_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_content_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_completed_date_utc'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_completed_at'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_xp_event_user_id'), table_name='xp_event')
    op.drop_index('ix_xp_event_user_date', table_name='xp_event')
    op.drop_index(op.f('ix_xp_event_created_date_utc'), table_name='xp_event')
    op.drop_table('xp_event')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_video_content_status'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_published_at'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_level'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_language'), table_name='video_content')
    op.drop_index('ix_video_content_feed', table_name='video_content')
    op.drop_index(op.f('ix_video_content_creator_id'), table_name='video_content')
    op.drop_table('video_content')
    op.drop_table('streak')
    op.drop_index(op.f('ix_learner_profile_target_language'), table_name='learner_profile')
    op.drop_index(op.f('ix_learner_profile_level'), table_name='learner_profile')
    op.drop_table('learner_profile')
    op.drop_table('creator_profile')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
